LOCAL_PATH := device/cloudminds/aione


TARGET_BOARD_PLATFORM := msm8996

TARGET_DEVICE := aione


TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := kryo


TARGET_PREBUILT_KERNEL := \
$(LOCAL_PATH)/prebuilt/kernel


BOARD_KERNEL_PAGESIZE := 4096

BOARD_KERNEL_OFFSET := 0x00080000
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_TAGS_OFFSET := 0x00000100


TARGET_RECOVERY_FSTAB := \
$(LOCAL_PATH)/rootdir/etc/recovery.fstab


BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864


TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := false


TW_THEME := portrait_hdpi


TARGET_USES_QCOM_BSP := true


BOARD_HAS_NO_SELECT_BUTTON := true

TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888

TW_MAX_BRIGHTNESS := 255

TW_DEFAULT_BRIGHTNESS := 100

TW_NO_SCREEN_BLANK := true

TW_NO_USB_STORAGE := true